import type { GameplayTuning } from './gameplayConfig.types';

export const GAMEPLAY_DEFAULTS: GameplayTuning = {
  playerMoveSpeed: 240,
  playerRadius: 18,
  playerAcceleration: 875,
  playerPassiveDeceleration: 282,
  playerStopDeceleration: 740,
  playerStopMinSpeed: 90,
  playerStopEntryAngleThreshold: 2.18,
  playerStopDuration: 0.28,
  playerStopRecoveryDuration: 0.18,
  playerStopLateralSlideFactor: 0.12,
  playerStopBodyLean: 0.38,
  playerStopShoulderOpen: 0.24,
  playerStopStickStability: 0.52,
  playerStopSprayDuration: 0.15,
  playerStopSprayStrength: 0.92,
  playerTraction: 4.15,
  playerRotationSpeed: 4.35,
  playerLowSpeedRotationSpeed: 7.95,
  playerTurnPenalty: 0.34,
  playerCarveResponse: 0.085,
  playerTurnRateMin: 4.35,
  playerTurnRateMax: 7.95,
  playerEdgeBoostAmount: 0.056,

  aimEnabled: true,
  aimDeadzonePx: 32,
  hideSystemCursor: true,
  crosshairEnabled: true,
  crosshairSize: 16,
  crosshairThickness: 2,
  crosshairCenterGap: 4,

  stickOffsetX: 0,
  stickOffsetY: 0,
  stickLength: 0,
  stickTipRadius: 0,
  stickVisualLag: 0,
  stickVisualLagMaxDeg: 0,
  drawStickTarget: false,
  drawStickHitbox: false,

  puckRadius: 8,
  puckMaxSpeed: 560,
  puckLinearDamping: 0.52,
  puckRestitution: 0.52,
  puckSurfaceDrag: 0.0035,

  puckPickupRadius: 22,
  puckPickupMaxSpeed: 220,
  puckPickupMaxRelativeSpeed: 240,
  puckMagnetRadius: 30,
  puckMagnetStrength: 90,
  puckMagnetMaxForce: 120,
  puckHoldSpringK: 28,
  puckHoldDampingC: 10,
  puckHoldMaxError: 46,
  puckPickupCooldownMs: 280,

  puckShotBaseImpulse: 110,
  puckShotChargeRate: 1.65,
  puckShotChargeMult: 990,
  puckShotMaxImpulse: 1100,
  puckShotMinHoldMs: 0,
  puckOneTimerGraceMs: 200,
  puckDrawPickupRadius: false,
  puckDrawMagnetRadius: false,
  puckDrawState: false,
  puckDrawVelocity: false,

  crosscheckWindupSec: 0.08,
  crosscheckActiveSec: 0.10,
  crosscheckRecoverySec: 0.22,
  crosscheckForwardOffset: 24,
  crosscheckHalfWidth: 18,
  crosscheckHitRadius: 10,
  crosscheckShoveSpeed: 86,
  crosscheckDummyShoveMultiplier: 1.18,
  crosscheckSeparationPadding: 4,
  dummyAutoResetSec: 1.25,

  __version: 1
};
