import type { PlayerStateMsg } from '@flathockey/shared';

export type PredictedPlayerState = PlayerStateMsg & {
  stamina?: number;
  heading?: number;
  headingOmega?: number;
  desiredHeadingAngle?: number;
  movementModelActive?: 'LEGACY' | 'V3' | 'V4' | 'SKATE_STEERING' | 'DESIRED_HEADING_TRACTION';
  moveAngle?: number;
  inputAngle?: number;
  desiredDirX?: number;
  desiredDirY?: number;
  committedDirX?: number;
  committedDirY?: number;
  distanceSinceCommit?: number;
  reverseDriveState?: 'NORMAL' | 'TRANSITION_TO_REVERSE' | 'REVERSE_READY';
  commitNoInputTimer?: number;
  reverseTransitionActive?: boolean;
  reverseTransitionTimer?: number;
  pendingDirX?: number;
  pendingDirY?: number;
  directionCommitTimer?: number;
  oppositeHoldTimer?: number;
  carveLockTimer?: number;
  carveSwitchCooldownTimer?: number;
  carveSide?: -1 | 0 | 1;
  movementPhase?: 'GLIDE' | 'CARVE_LEFT' | 'CARVE_RIGHT' | 'BRAKE';
  startCommitTimer?: number;
  startNoInputTimer?: number;
  startupOppositeLockTimer?: number;
  startupLatchActive?: boolean;
  startupReleaseTimer?: number;
  startDirX?: number;
  startDirY?: number;
  lastStableTravelAngle?: number;
  lastRawInputAngle?: number;
  antiFlipTimer?: number;
  baseBodyAngle?: number;
  bodyYawOffset?: number;
  bodyTargetAngle?: number;
  aimAngle?: number;
  aimAngleRaw?: number;
  stickAngVel?: number;
  stickLocalAngle?: number;
  prevHasInput?: boolean;
  brakeAssistLeft?: number;
  startLinearActive?: boolean;
  stickSide?: -1 | 1;
  chargeActive?: boolean;
  stunLeft?: number;
  debugSnapFactor?: number;
  debugBrakeAssistActive?: boolean;
  debugStartModeActive?: boolean;
  debugVelForward?: number;
  debugVelSide?: number;
  debugStickDeltaDeg?: number;
  debugStickAngVelDeg?: number;
  debugStickAngVelClamped?: boolean;
  debugStickTargetSlewActive?: boolean;
  debugStickMode?: 'TAU' | 'SPRING' | 'APPROACH';
  debugTargetAimAngle?: number;
  debugRawInputAngle?: number;
  debugDesiredMoveAngle?: number;
  debugTurnIntentAngle?: number;
  debugMoveTurnRateAppliedDeg?: number;
  debugVelocityDesiredDeltaDeg?: number;
  debugTurnResistance?: number;
  debugRedirectAccelScale?: number;
  debugAntiFlipActive?: boolean;
  debugDesiredInputX?: number;
  debugDesiredInputY?: number;
  debugRequestedInputDirX?: number;
  debugRequestedInputDirY?: number;
  debugAppliedForwardForce?: number;
  debugAppliedLateralForce?: number;
  debugCommitTimer?: number;
  debugOppositeHoldTimer?: number;
  debugSteerDirX?: number;
  debugSteerDirY?: number;
  debugMinSteerSpeed?: number;
  debugLowSpeedSteeringDisabled?: boolean;
  debugLowSpeedStartupActive?: boolean;
  debugTravelDirLocked?: boolean;
  debugStartupLatchActive?: boolean;
  debugLatchedInputIgnored?: boolean;
  debugStartupReleaseTimer?: number;
  debugStartCommitActive?: boolean;
  debugStartCommitTimer?: number;
  debugStartDirX?: number;
  debugStartDirY?: number;
  debugEffectiveStartDirX?: number;
  debugEffectiveStartDirY?: number;
  debugMovementPhase?: 'GLIDE' | 'CARVE_LEFT' | 'CARVE_RIGHT' | 'BRAKE';
  debugCarveLockTimer?: number;
  debugCarveSide?: -1 | 0 | 1;
  debugSignedInputVsVelocityAngle?: number;
  debugMajorDirectionChangeBlocked?: boolean;
  debugBrakeActive?: boolean;
  debugReverseTransitionActive?: boolean;
  debugSharpRedirectGated?: boolean;
  debugAngularCapDegPerSec?: number;
  debugCommittedDriveAngle?: number;
  debugDesiredDriveAngle?: number;
  debugDriveCommitLocked?: boolean;
  debugReverseState?: 'NORMAL' | 'TRANSITION_TO_REVERSE' | 'REVERSE_READY';
  debugOppositeIntentBlocked?: boolean;
  debugCommitUnlockReason?: 'NONE' | 'LOW_SPEED' | 'DISTANCE_RELAXED' | 'BRAKE_REVERSE_READY';
  debugMinHeadingAuthorityActive?: boolean;
  debugMovementModel?: 'skateSteering' | 'desiredHeadingTraction';
  debugHeadingAngle?: number;
  debugHeadingOmega?: number;
  debugForwardSpeed?: number;
  debugLateralSpeed?: number;
  debugDesiredHeadingAngle?: number;
  debugHeadingErrorDeg?: number;
  debugSteerInput?: number;
  debugThrottleInput?: number;
  debugBaseBodyAngle?: number;
  debugBodyYawOffset?: number;
  debugBodyTurnInput?: number;
  debugActiveBodyModel?: 'B' | 'C';
};
